# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

logDensitiesMaxDiff <- function(e_u, weights, is_tricked = FALSE) {
    .Call(`_flipMaxDiff_logDensitiesMaxDiff`, e_u, weights, is_tricked)
}

logDensityMaxDiff <- function(e_u, weights, is_tricked = FALSE) {
    .Call(`_flipMaxDiff_logDensityMaxDiff`, e_u, weights, is_tricked)
}

gradientMaxDiff <- function(e_u, x, weights, n_pars, is_tricked) {
    .Call(`_flipMaxDiff_gradientMaxDiff`, e_u, x, weights, n_pars, is_tricked)
}

logKernels <- function(beta_draws, x, weights, is_tricked = FALSE) {
    .Call(`_flipMaxDiff_logKernels`, beta_draws, x, weights, is_tricked)
}

sumWeightedOuterProducts <- function(beta_draws, weights) {
    .Call(`_flipMaxDiff_sumWeightedOuterProducts`, beta_draws, weights)
}

