# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

logDensityBestWorst <- function(e_u, weights) {
    .Call('flipMaxDiff_logDensityBestWorst', PACKAGE = 'flipMaxDiff', e_u, weights)
}

